project:
  type: website
  output-dir: docs

jupyter:
  kernel: eds232_env

website:
  navbar:
    title: "EDS 232"
    right:
      - href: index.qmd
        text: Home
      - text: Discussion
        menu:
          - text: Week 1
            href: discussion/week1.qmd
          - text: Week 2 
            href: discussion/week2.qmd
          - text: Week 3
            href: discussion/week3.qmd
          - text: Week 4
            href: discussion/week4.qmd
          - text: Week 6
            href: discussion/week6.qmd
          - text: Week 7
            href: discussion/week7.qmd
          - text: Week 8
            href: discussion/week8.qmd
          - text: Week 9
            href: discussion/week9.qmd
            
            
      - text: Weekly Labs
        menu:
          - text: Lab Rubric
            href: www/lab_rubric.pdf
          - text: Weekly Labs
            href: labs/lab_instructions.qmd     
     
      - icon: github
        href: https://github.com/MaRo406/eds-232-machine-learning
        target: _blank

  page-footer:
    background: dark

format:
  html:
    theme: meds-website-styles.scss
    toc: true
    toc-location: left
    title-block-banner: true
    page-layout: full

editor: source
